server:
    port: 8086

spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost/postgres
        username: root
        password: testtest
    liquibase:
        enabled: true

logging:
    level:
        root: info


