server:
    port: 8086

spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://195.133.48.174:5432/social
        username: javapro
        password: admin
    liquibase:
        enabled: true

logging:
    level:
        root: info

yandexprofile:
    login: javaproteams27@yandex.ru
    token: y0_AgAAAABkHWYcAAhcJAAAAADNMMSQdTIhTbQjRfCCNvyw30mWw_U7WIY

redis:
  url: redis://195.133.48.174:6379

logsupload:
    enabled: false

management:
  endpoints:
      web:
          exposure:
              include: 'prometheus, health'
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
global:
  scrape_interval:     5s # By default, scrape targets every 15 seconds.
  external_labels:
    monitor: 'codelab-monitor'
scrape_configs:
  - job_name: 'taxi-servce'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['195.133.48.174:8080']

