server:
    port: 8086

spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://195.133.48.174:5432/social
        username: javapro
        password: admin
    liquibase:
        enabled: true

logging:
    level:
        root: info

yandexprofile:
    login: javaproteams27@yandex.ru
    token: y0_AgAAAABkHWYcAAhcJAAAAADNMMSQdTIhTbQjRfCCNvyw30mWw_U7WIY

logsupload:
    enabled: false